[dependencies]
anyhow = {workspace = true}
config = {version = "0.14.0", features = ["json5"]}
json5 = "0.4.1"
reqwest = {workspace = true}
serde = {workspace = true}
tracing = {workspace = true}

[package]
edition = "2021"
name = "app-config"
publish = false
version = "0.1.0"
